name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

- name: rust-cargo
  # You may pin to the exact commit or the version.
  # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
  uses: actions-rs/cargo@v1.0.1
  with:
    # Cargo command to run (ex. `check` or `build`)
    command: 
    # Toolchain to use (without the `+` sign, ex. `nightly`)
    toolchain: # optional
    # Arguments for the cargo command
    args: # optional
    # Use cross instead of cargo
    use-cross: # optional
